[[redirects]]
  from = "/delivery-payment"
  to = "/delivery-payment.html"
  status = 200
  force = true

[[redirects]]
  from = "/delivery-payment/"
  to = "/delivery-payment.html"
  status = 200
  force = true

[[redirects]]
  from = "/warranty-return"
  to = "/warranty-return.html"
  status = 200
  force = true

[[redirects]]
  from = "/warranty-return/"
  to = "/warranty-return.html"
  status = 200
  force = true

[[redirects]]
  from = "/reviews"
  to = "/reviews.html"
  status = 200
  force = true

[[redirects]]
  from = "/reviews/"
  to = "/reviews.html"
  status = 200
  force = true

[[redirects]]
  from = "/contacts"
  to = "/contacts.html"
  status = 200
  force = true

[[redirects]]
  from = "/contacts/"
  to = "/contacts.html"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
  force = true

[[redirects]]
  from = "/about/"
  to = "/about.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy/"
  to = "/privacy.html"
  status = 200
  force = true
